ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "two_factor_enabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "otp_hash"           TEXT,
  ADD COLUMN IF NOT EXISTS "otp_expires_at"     TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "otp_attempts"       INTEGER NOT NULL DEFAULT 0;
